/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { ChevronDown, Layers, Sparkles } from 'lucide-react'
import { useTranslation } from 'react-i18next'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible'
import { cn } from '@/lib/utils'

import type { ErrorSummaryProblem } from '../types'
import { ErrorMetricHelp } from './error-metric-help'

type ErrorProblemOverviewProps = {
  problems: ErrorSummaryProblem[]
  briefingAvailable: boolean
  briefing: string
  briefingModel: string
  briefingCached: boolean
  briefingLoading: boolean
  briefingError: string
  onGenerateBriefing: () => void
  onSelectProblem: (problem: ErrorSummaryProblem) => void
}

const severityClassNames: Record<string, string> = {
  critical: 'border-red-300 bg-red-50 text-red-800 dark:bg-red-950/30',
  high: 'border-orange-300 bg-orange-50 text-orange-800 dark:bg-orange-950/30',
  medium: 'border-amber-300 bg-amber-50 text-amber-800 dark:bg-amber-950/30',
  low: 'border-border bg-muted/40 text-muted-foreground',
}

export function ErrorProblemOverview(props: ErrorProblemOverviewProps) {
  const { t } = useTranslation()

  if (props.problems.length === 0) {
    return null
  }

  const severityLabels: Record<string, string> = {
    critical: t('Critical'),
    high: t('High'),
    medium: t('Medium'),
    low: t('Low'),
  }

  return (
    <section className='shrink-0 rounded-lg border'>
      <div className='flex flex-wrap items-center justify-between gap-2 border-b px-3 py-2.5'>
        <h2 className='flex items-center gap-2 text-sm font-semibold'>
          <Layers className='text-muted-foreground size-4' />
          <ErrorMetricHelp
            description={t(
              'Problems fold the fault clusters by what they share. One channel failing the same way across several models becomes a single channel problem; one model failing across several channels becomes a single model problem. Every cluster belongs to exactly one problem.'
            )}
          >
            {t('Problems')}
          </ErrorMetricHelp>
          <span className='text-muted-foreground font-normal tabular-nums'>
            {props.problems.length}
          </span>
        </h2>
        {props.briefingAvailable && (
          <Button
            type='button'
            size='sm'
            variant='outline'
            onClick={props.onGenerateBriefing}
            disabled={props.briefingLoading}
          >
            <Sparkles
              className={cn('size-4', props.briefingLoading && 'animate-pulse')}
            />
            {props.briefingLoading
              ? t('Generating briefing...')
              : t('Generate AI briefing')}
          </Button>
        )}
      </div>

      {(props.briefing || props.briefingError) && (
        <div className='border-b px-3 py-2.5'>
          {props.briefingError ? (
            <p className='text-destructive text-xs'>{props.briefingError}</p>
          ) : (
            <>
              <p className='text-sm leading-6 whitespace-pre-wrap'>
                {props.briefing}
              </p>
              <p className='text-muted-foreground mt-1.5 text-xs'>
                {t('Generated by')} {props.briefingModel}
                {props.briefingCached ? ` · ${t('cached')}` : ''}
              </p>
            </>
          )}
        </div>
      )}

      <Collapsible defaultOpen>
        <CollapsibleTrigger
          render={
            <button
              type='button'
              className='hover:bg-muted/50 text-muted-foreground flex w-full items-center gap-1.5 px-3 py-2 text-xs transition-colors'
            >
              <ChevronDown className='size-3.5' />
              {t('Show folded problems')}
            </button>
          }
        />
        <CollapsibleContent>
          <div className='max-h-56 divide-y overflow-y-auto border-t'>
            {props.problems.map((problem) => {
              let primary = problem.model_name || problem.channel_name || '-'
              let secondary =
                problem.channel_name && problem.model_name
                  ? problem.channel_name
                  : ''
              if (problem.scope === 'channel') {
                primary = problem.channel_name || `#${problem.channel}`
                secondary =
                  problem.affected_models.length > 1
                    ? t('{{count}} models', {
                        count: problem.affected_models.length,
                      })
                    : ''
              } else if (problem.scope === 'model') {
                primary = problem.model_name
                secondary =
                  problem.affected_channels.length > 1
                    ? t('{{count}} channels', {
                        count: problem.affected_channels.length,
                      })
                    : ''
              }
              return (
                <button
                  key={problem.key}
                  type='button'
                  onClick={() => props.onSelectProblem(problem)}
                  className='hover:bg-muted/50 focus-visible:ring-ring flex w-full flex-wrap items-center gap-2 px-3 py-2 text-left text-xs transition-colors focus-visible:ring-2 focus-visible:outline-none'
                >
                  <Badge
                    variant='outline'
                    className={cn(
                      'text-[11px]',
                      severityClassNames[problem.severity] ??
                        severityClassNames.low
                    )}
                  >
                    {severityLabels[problem.severity] ?? t('Low')}
                  </Badge>
                  {problem.status_code > 0 && (
                    <Badge variant='outline' className='font-mono text-[11px]'>
                      {problem.status_code}
                    </Badge>
                  )}
                  <span className='min-w-0 truncate font-medium'>
                    {primary}
                  </span>
                  {secondary && (
                    <span className='text-muted-foreground shrink-0'>
                      {secondary}
                    </span>
                  )}
                  <span className='text-muted-foreground ml-auto shrink-0 tabular-nums'>
                    {t('{{count}} clusters', { count: problem.cluster_count })}
                    {' · '}
                    {t('{{count}} requests', {
                      count: problem.affected_requests,
                    })}
                  </span>
                </button>
              )
            })}
          </div>
        </CollapsibleContent>
      </Collapsible>
    </section>
  )
}
