/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { Sparkles, X } from 'lucide-react'
import { useTranslation } from 'react-i18next'

import { Button } from '@/components/ui/button'
import { Markdown } from '@/components/ui/markdown'

type ErrorBriefingBandProps = {
  briefing: string
  briefingModel: string
  briefingCached: boolean
  briefingError: string
  onDismiss: () => void
}

/**
 * The generated briefing summarizes the whole filtered view, not one cluster,
 * so it sits above the split rather than inside either pane. It only takes
 * height once a briefing exists, so the work area stays full-size by default.
 * The briefing is markdown (bold entities, one list item per problem), so it
 * renders through Markdown instead of a plain pre-wrap paragraph.
 */
export function ErrorBriefingBand(props: ErrorBriefingBandProps) {
  const { t } = useTranslation()

  if (!props.briefing && !props.briefingError) {
    return null
  }

  return (
    <section className='border-primary/25 bg-primary/5 shrink-0 rounded-lg border px-3 py-2.5'>
      <div className='flex items-start gap-2'>
        <Sparkles className='text-primary mt-0.5 size-4 shrink-0' />
        <div className='min-w-0 flex-1'>
          {props.briefingError ? (
            <p className='text-destructive text-xs'>{props.briefingError}</p>
          ) : (
            <>
              <div className='mb-1 flex flex-wrap items-baseline gap-x-2'>
                <span className='text-sm font-semibold'>
                  {t('AI briefing')}
                </span>
                <span className='text-muted-foreground text-xs'>
                  {t('Generated by')} {props.briefingModel}
                  {props.briefingCached ? ` · ${t('cached')}` : ''}
                </span>
              </div>
              <Markdown className='[&_li]:my-0.5 [&_p]:my-1 [&_p]:text-sm [&_ul]:my-1 [&_ul]:text-sm [&_strong]:text-foreground text-sm'>
                {props.briefing}
              </Markdown>
            </>
          )}
        </div>
        <Button
          type='button'
          size='icon'
          variant='ghost'
          className='size-7 shrink-0'
          aria-label={t('Dismiss briefing')}
          onClick={props.onDismiss}
        >
          <X className='size-4' />
        </Button>
      </div>
    </section>
  )
}
